
module.exports = {
    Success: 200,
    MissingInput: -400,
	Unauthorized: -401,
	NotFound: -404,
	InternalServerError: -500,
	TaskNotDisabled: -1,
	TaskHasActiveJobs: -2,
	JobAlreadyCanceled: -3,
	JobAlreadyCompleted: -4,
	EmptyAsset: -5,
	TaskAlreadyExists: -8,
	TaskNoInputParameter: -9,
	TaskNoOutputParameter: -10,
	InvalidStartUrl: -11,
	InvalidCancelUrl: -12,
	InvalidInput: -13,
	InvalidPublicationdate: -14,
	InvalidExpirationDate: -15,
	JobStatusNotUpdatable: -16,
	ForbiddenAsset: -17,
	InvalidOutput: -18,
	NotCompletable: -19,
	LinkedParameterNotTheSameType: -20,
	LinkedOutputNotFound: -21,
	ServiceNameInUse: -22,
	ContentOwnerNameExists: -23,
	ContentOwnerUsernameExists: -24,
	ContentOwnerEmailExists: -25,
	JobWithDisabledTasks: -26,
	PasswordIsTooShort: -27,
	InvalidCredentials: -28,
	NewPasswordDoesntMatchVerification: -29,
}